var gdata = {
"graphset":[
    {
        "type":"area",
        "stacked":true,
        "background-color":"#ffffff",
        "alpha":1,
        "title":{
            "text":"Browser Usage",
            "font-family":"helvetica",
            "font-size":"20px",
            "font-weight":"bold",
            "font-color":"#000000",
            "background-color":"#ffffff",
            "margin-top":"15px",
            "margin-left":"15px",
            "margin-bottom":"10px",
            "text-align":"left"
        },
        "legend":{
            "layout":"vertical",
            "margin":"2 5 5 380",
            "visible":true,
            "shadow":false,
            "font-family":"arial",
            "font-size":"10px",
            "background-color":"#ffffff",
            "border-width":"0px",
            "item":{
                "padding":"-2 2",
                "border-width":"0px"
            }
        },
        "scale-x":{
            "line-width":"1px",
            "line-color":"#CCCCCC",
            "line-style":"solid",
            "values":["Jan","Feb","Mar","Apr","May","Jun"],
            "guide":{
                "line-color":"#000000",
                "alpha":0.1,
                "line-style":"solid"
            },
            "tick":{
                "visible":false
            },
            "item":{
                "font-family":"helvetica",
                "font-color":"#CCCCCC",
                "font-weight":"bold",
                "font-size":"10px",
                "visible":true
            }
        },
        "scale-y":{
            "line-width":"1px",
            "line-color":"#CCCCCC",
            "line-style":"solid",
            "format":"%v",
            "tick":{
                "visible":true,
                "line-color":"#CCCCCC",
                "placement":"outer",
                "size":"12px"
            },
            "item":{
                "font-family":"helvetica",
                "font-color":"#CCCCCC",
                "font-weight":"bold",
                "font-size":"10px",
                "visible":true
            },
            "guide":{
                "line-color":"#000000",
                "alpha":0.1,
                "line-style":"solid"
            }
        },
        "crosshair-x":{
            "line-width":2,
            "line-color":"#FFFFFF",
            "alpha":"0.3",
            "shadow":true,
            "shadow-alpha":"0.5",
            "shadow-distance":"3px",
            "valuel-label":{
                "font-color":"#000000"
            },
            "scale-label":{
                "visible":false
            },
            "marker":{
                "visible":false
            }
        },
        "plot":{
            "alpha-area":0.5,
            "alpha":1,
            "tooltip-text":" %t: %v downloads"
        },
        "tooltip":{
            "visible":false
        },
        "series":[
            {
                "values":[18,25,19,7,20,16],
                "text":"Explorer",
                "background-color":"#7eac10",
                "marker":{
                    "type":"circle",
                    "size":5,
                    "background-color":"#7eac10",
                    "border-width":1,
                    "border-color":"#ffffff"
                }
            },
            {
                "values":[21,15,26,23,27,22],
                "text":"Firefox",
                "background-color":"#1a87d5",
                "marker":{
                    "type":"circle",
                    "size":5,
                    "background-color":"#1a87d5",
                    "border-width":1,
                    "border-color":"#ffffff"
                }
            }
        ]
    }
]
}