var gdata = {
"graphset":[
    {
        "type":"bar",
        "alpha":1,
        "border-color":"-1",
        "border-width":"0px",
        "background-image":"images/blue_bg.jpg",
        "plotarea":{
            "margin":"80px 60px 80px 70px"
        },
        "title":{
            "text":"SOCIAL NETWORKS",
            "font-family":"georgia",
            "font-size":"20px",
            "font-style":"italic",
            "font-color":"#64ADC0",
            "margin-left":"110px",
            "margin-top":"20px",
            "text-align":"left",
            "background-color":-1
        },
        "legend":{
            "layout":"1",
            "margin-top":"360px",
            "margin-left":"100px",
            "width":"345px",
            "height":"30px",
            "visible":true,
            "font-family":"georgia",
            "font-size":"10px",
            "background-color":"#D7F2F5",
            "border-color":"#EBF3FA",
            "shadow":false,
            "item":{
                "padding":"2",
                "border-radius":"10px",
                "marker-style":"circle",
                "border-width":"0px",
                "font-size":"9px",
                "font-family":"georgia"
            }
        },
        "scale-x":{
            "values":["Jan","Feb","Mar","Apr"],
            "line-color":"#85C4DA",
            "alpha":1,
            "minor-ticks":4,
            "line-style":"solid",
            "guide":{
                "line-color":"#85C4DA",
                "alpha":1,
                "line-style":"solid"
            },
            "tick":{
                "line-width":"1px",
                "line-color":"#85C4DA"
            },
            "minor-tick":{
                "line-color":"#FA9024",
                "size":"3px",
                "line-width":"1px"
            },
            "item":{
                "font-size":"12px",
                "font-color":"#888888",
                "font-weight":"bold",
                "font-family":"georgia"
            },
            "minor-guide":{
                "visible":true,
                "line-color":"#85C4DA"
            }
        },
        "scale-y":{
            "line-width":"1px",
            "line-color":"#85C4DA",
            "minor-ticks":1,
            "format":"%v",
            "guide":{
                "line-color":"#85C4DA",
                "alpha":1,
                "line-style":"solid"
            },
            "tick":{
                "line-width":"1px",
                "line-color":"#85C4DA"
            },
            "minor-tick":{
                "line-color":"#FA9024",
                "size":"3px",
                "line-width":"1px"
            },
            "item":{
                "font-size":"12px",
                "font-color":"#888888",
                "font-family":"georgia"
            },
            "minor-guide":{
                "visible":true,
                "line-color":"#85C4DA"
            }
        },
        "tooltip":{
            "visible":true,
            "border-radius":"1px",
            "border-width":"2px",
            "border-color":"#FFFFFF"
        },
        "plot":{
            "alpha":1,
            "animate":true,
            "tooltip-text":"%t:%v",
            "speed":0.8,
            "effect":4,
            "border-color":"#FFFFFF",
            "border-width":"3px"
        },
        "series":[
            {
                "values":[22,28,38,44],
                "background-color":"#85C4DA",
                "text":"Facebook"
            },
            {
                "values":[18,13,16,11],
                "background-color":"#FA9024",
                "text":"MySpace"
            },
            {
                "values":[12,22,13,15],
                "background-color":"#3DD6A8",
                "text":"Orkut"
            },
            {
                "values":[3,12,8,13],
                "background-color":"#E09FAF",
                "text":"hi5"
            }
        ]
    }
]
}