var gdata = {
"graphset":[
    {
        "type":"line",
        "background-color":"#ffffff",
        "alpha":1,
        "title":{
            "text":"Browser Usage",
            "font-family":"helvetica",
            "font-size":"20px",
            "font-weight":"bold",
            "font-color":"#000000",
            "background-color":"#ffffff",
            "margin-top":"15px",
            "margin-left":"15px",
            "margin-bottom":"10px",
            "text-align":"left"
        },
        "legend":{
            "layout":"vertical",
            "margin":"2 5 5 380",
            "visible":true,
            "shadow":false,
            "font-family":"arial",
            "font-size":"10px",
            "background-color":"#ffffff",
            "border-width":"0px",
            "item":{
                "padding":"-2 2",
                "border-width":"0px"
            }
        },
        "scale-x":{
            "line-width":"1px",
            "line-color":"#CCCCCC",
            "line-style":"solid",
            "values":["Jan","Feb","Mar","Apr","May","Jun"],
            "guide":{
                "alpha":0.4,
                "visible":true,
                "line-width":"1px",
                "line-color":"#CCCCCC",
                "line-style":"solid"
            },
            "tick":{
                "visible":false
            },
            "item":{
                "font-family":"helvetica",
                "font-color":"#CCCCCC",
                "font-weight":"bold",
                "font-size":"10px",
                "visible":true
            }
        },
        "scale-y":{
            "values":"0:50:10",
            "line-width":"1px",
            "line-color":"#CCCCCC",
            "line-style":"solid",
            "format":"%v",
            "tick":{
                "visible":true,
                "line-color":"#CCCCCC",
                "placement":"outer",
                "size":"12px"
            },
            "item":{
                "font-family":"helvetica",
                "font-color":"#CCCCCC",
                "font-weight":"bold",
                "font-size":"10px",
                "visible":true
            },
            "guide":{
                "alpha":0.4,
                "visible":true,
                "line-width":"1px",
                "line-color":"#CCCCCC",
                "line-style":"solid"
            }
        },
        "tooltip":{
            "font-family":"helvetica",
            "font-weight":"bold",
            "visible":true,
            "background-color":"#ffffff",
            "border-color":"#000000",
            "font-color":"#000000",
            "border-width":"1px"
        },
        "plot":{
            "alpha":1,
            "tooltip-text":" %t <br/>%v downloads <br/> Month: %k",
            "marker":{
                "type":"circle",
                "size":5,
                "border-width":1,
                "border-color":"#ffffff"
            }
        },
        "series":[
            {
                "values":[28,35,19,27,30,46],
                "text":"Explorer",
                "background-color":"#7eac10",
                "marker":{
                    "background-color":"#7eac10"
                }
            },
            {
                "values":[40,33,26,23,27,22],
                "text":"Firefox",
                "background-color":"#1a87d5",
                "marker":{
                    "background-color":"#1a87d5"
                }
            }
        ]
    }
]
}