var gdata = {
"graphset":[
    {
        "type":"line",
        "alpha":1,
        "background-color":"#121212",
        "plotarea":{
            "margin":"75 45 75 100"
        },
        "title":{
            "text":"Stock Market Crash of April 05",
            "font-family":"Arial",
            "font-size":"22px",
            "font-color":"#fe7e00",
            "font-weight":"bold",
            "background-color":"#121212",
            "margin-top":"15px",
            "margin-left":"45px",
            "margin-bottom":"10px",
            "text-align":"center"
        },
        "scale-x":{
            "min-value":1104537600000,
            "max-items":7,
            "step":604800000,
            "line-color":"#ffffff",
            "line-style":"solid",
            "line-width":"1px",
            "guide":{
                "line-color":"#ffffff",
                "line-width":"1px",
                "alpha":0.2,
                "line-style":"dotted"
            },
            "tick":{
                "line-width":"2px",
                "line-color":"#ffffff"
            },
            "minor-ticks":1,
            "minor-tick":{
                "alpha":1,
                "placement":"outer",
                "line-color":"#ffffff"
            },
            "minor-guide":{
                "visible":false
            },
            "item":{
                "font-size":"14px",
                "font-color":"#ffffff",
                "font-weight":"bold",
                "font-family":"arial"
            },
            "transform":{
                "type":"date",
                "all":"%M %y",
                "guide":{
                    "visible":false
                },
                "item":{
                    "visible":false
                }
            }
        },
        "scale-y":{
            "values":"1000:5000:500",
            "line-width":"1px",
            "line-color":"#808080",
            "format":"%v",
            "line-style":"solid",
            "decimals":2,
            "decimals-separator":".",
            "thousands-separator":",",
            "guide":{
                "visible":true,
                "line-color":"#ffffff",
                "line-width":"1px",
                "alpha":0.2,
                "line-style":"dotted"
            },
            "tick":{
                "line-width":"2px",
                "line-color":"#ffffff"
            },
            "minor-ticks":1,
            "minor-tick":{
                "placement":"outer",
                "alpha":1,
                "line-color":"#ffffff"
            },
            "item":{
                "font-size":"14px",
                "font-color":"#ffffff",
                "font-weight":"bold",
                "font-family":"arial"
            },
            "minor-guide":{
                "visible":false
            },
            "label":{
                "text":"Index",
                "font-size":"14px",
                "font-family":"Arial",
                "font-weight":"bold",
                "font-color":"#3384f2"
            }
        },
        "crosshair-x":{
            "marker":{
                "visible":false
            },
            "value-label":{
                "text-align":"center",
                "border-width":"2px",
                "font-size":"12px",
                "border-color":"#ffffff",
                "font-color":"#000000",
                "background-color":"#ffffff",
                "text":"%t: %v"
            },
            "scale-label":{
                "visible":false
            }
        },
        "tooltip":{
            "visible":false
        },
        "plot":{
            "line-width":"2px",
            "line-color":"#ffffff",
            "shadow":false,
            "alpha":1,
            "marker":{
                "visible":false
            }
        },
        "series":[
            {
                "values":[2000,3300,4600,3570,2900,3605,2750,3300,2846,4400,3400,3600,4200,4500,3000,3502,1200,1400,2100,5000,4300,3300,2800,2900,2700],
                "line-width":"1px",
                "line-style":"dashed",
                "line-color":"#ffffff",
                "text":"PETR4"
            },
            {
                "values":[3600,3000,4500,3000,1500,1200,1400,1100,1500,1300,3300,2800,2900,2700,2000,1300,1600,1500,2900,3200,3400,3300,2100,4400,3400],
                "line-width":"1px",
                "line-style":"solid",
                "line-color":"#fe7e00",
                "text":"MMXM3"
            }
        ]
    }
]
}