var gdata = {
	"tooltip":{},
    "shapes":[
    	{
	    	"type":"zingchart.maps",
	    	"options":{
	    		"id":"map",
	    		"name":"usa",
	    		"x":0,
	    		"y":0,
	    		"width":640,
	    		"height":430,
		    	"style":{
		    		"hoverState":{
		    			"visible":false
		    		}
		    	}
	    	}
    	}
	]
}