<cfmail to="adam@straker.co.nz" from="hotshot@straker.co.nz" subject="" server="192.168.5.11">
	<cfscript>
		writeOutput("This string is generated by this code: writeOutput(""This string is generated by this code:"");");
	</cfscript>
</cfmail>