{
"Great Britain": {"size":"542"},
"United States of America": {"size":"530"},
"Russian Federation": {"size":"436"},
"Australia": {"size":"410"},
"Germany": {"size":"392"},
"People's Republic of China": {"size":"386"},
"France": {"size":"333"},
"Japan": {"size":"293"},
"Italy": {"size":"284"},
"Spain": {"size":"282"},
"Canada": {"size":"277"},
"Brazil": {"size":"259"},
"Republic of Korea": {"size":"245"},
"Ukraine": {"size":"240"},
"Poland": {"size":"217"},
"New Zealand": {"size":"184"},
"Netherlands": {"size":"178"},
"Belarus": {"size":"166"},
"Hungary": {"size":"158"},
"Argentina": {"size":"137"},
"Sweden": {"size":"134"},
"Czech Republic": {"size":"133"},
"South Africa": {"size":"125"},
"Belgium": {"size":"115"},
"Serbia": {"size":"115"},
"Kazakhstan": {"size":"114"},
"Turkey": {"size":"114"},
"Denmark": {"size":"113"},
"Egypt": {"size":"113"},
"Cuba": {"size":"110"},
"Croatia": {"size":"108"},
"Colombia": {"size":"105"},
"Greece": {"size":"105"},
"Romania": {"size":"103"},
"Mexico": {"size":"102"},
"Switzerland": {"size":"102"},
"Tunisia": {"size":"83"},
"India": {"size":"81"},
"Portugal": {"size":"75"},
"Austria": {"size":"70"},
"Morocco": {"size":"69"},
"Venezuela": {"size":"69"},
"Ireland": {"size":"66"},
"Slovenia": {"size":"65"},
"Norway": {"size":"64"},
"Bulgaria": {"size":"63"},
"Lithuania": {"size":"62"},
"Finland": {"size":"55"},
"Nigeria": {"size":"55"},
"Uzbekistan": {"size":"54"},
"Azerbaijan": {"size":"53"},
"Iran": {"size":"53"},
"Democratic People's Republic  of Korea": {"size":"51"},
"Jamaica": {"size":"50"},
"Kenya": {"size":"47"},
"Latvia": {"size":"46"},
"Slovakia": {"size":"46"},
"Chinese Taipei": {"size":"44"},
"Hong Kong": {"size":"42"},
"Algeria": {"size":"39"},
"Israel": {"size":"37"},
"Thailand": {"size":"37"},
"Ecuador": {"size":"36"},
"Chile": {"size":"35"},
"Dominican Republic": {"size":"35"},
"Ethiopia": {"size":"35"},
"Georgia": {"size":"35"},
"Angola": {"size":"34"},
"Cameroon": {"size":"33"},
"Estonia": {"size":"33"},
"Montenegro": {"size":"33"},
"Senegal": {"size":"31"},
"Trinidad and Tobago": {"size":"31"},
"Malaysia": {"size":"30"},
"Mongolia": {"size":"29"},
"Uruguay": {"size":"29"},
"Honduras": {"size":"27"},
"Iceland": {"size":"27"},
"United Arab Emirates": {"size":"26"},
"Armenia": {"size":"25"},
"Gabon": {"size":"24"},
"Puerto Rico": {"size":"24"},
"Bahamas": {"size":"23"},
"Singapore": {"size":"23"},
"Republic of Moldova": {"size":"22"},
"Indonesia": {"size":"21"},
"Pakistan": {"size":"21"},
"Guatemala": {"size":"19"},
"Saudi Arabia": {"size":"19"},
"Vietnam": {"size":"18"},
"Peru": {"size":"16"},
"Tajikistan": {"size":"16"},
"Uganda": {"size":"16"},
"Bahrain": {"size":"14"},
"Kyrgyzstan": {"size":"14"},
"Cyprus": {"size":"13"},
"Eritrea": {"size":"12"},
"Qatar": {"size":"12"},
"Albania": {"size":"11"},
"Costa Rica": {"size":"11"},
"Kuwait": {"size":"11"},
"Mauritius": {"size":"11"},
"Philippines": {"size":"11"},
"El Salvador": {"size":"10"},
"Ivory Coast": {"size":"10"},
"Grenada": {"size":"10"},
"Lebanon": {"size":"10"},
"Syria": {"size":"10"},
"Turkmenistan": {"size":"10"},
"Fiji": {"size":"9"},
"Ghana": {"size":"9"},
"Luxembourg": {"size":"9"},
"Jordan": {"size":"9"},
"Namibia": {"size":"9"},
"Bermuda": {"size":"8"},
"Cook Islands": {"size":"8"},
"Guam": {"size":"8"},
"Iraq": {"size":"8"},
"Papua New Guinea": {"size":"8"},
"Paraguay": {"size":"8"},
"Samoa": {"size":"8"},
"Zambia": {"size":"8"},
"Zimbabwe": {"size":"8"},
"Congo": {"size":"7"},
"Madagascar": {"size":"7"},
"Panama": {"size":"7"},
"Rwanda": {"size":"7"},
"Saint Kitts and Nevis": {"size":"7"},
"Sri Lanka": {"size":"7"},
"Tanzania": {"size":"7"},
"Virgin Islands": {"size":"7"},
"Afghanistan": {"size":"6"},
"Andorra": {"size":"6"},
"Barbados": {"size":"6"},
"Bosnia and Herzegovina": {"size":"6"},
"Burundi": {"size":"6"},
"Cambodia": {"size":"6"},
"Central African Republic": {"size":"6"},
"Djibouti": {"size":"6"},
"Guyana": {"size":"6"},
"Libya": {"size":"6"},
"Mali": {"size":"6"},
"Micronesia": {"size":"6"},
"Monaco": {"size":"6"},
"Mozambique": {"size":"6"},
"Burma": {"size":"6"},
"Nicaragua": {"size":"6"},
"Niger": {"size":"6"},
"Seychelles": {"size":"6"},
"Sudan": {"size":"6"},
"Togo": {"size":"6"},
"Antigua and Barbuda": {"size":"5"},
"American Samoa": {"size":"5"},
"Bangladesh": {"size":"5"},
"Benin": {"size":"5"},
"Bolivia": {"size":"5"},
"Burkina Faso": {"size":"5"},
"Cayman Islands": {"size":"5"},
"Haiti": {"size":"5"},
"Maldives": {"size":"5"},
"Malta": {"size":"5"},
"Nepal": {"size":"5"},
"Palau": {"size":"5"},
"Palestine": {"size":"5"},
"Suriname": {"size":"5"},
"Vanuatu": {"size":"5"},
"Aruba": {"size":"4"},
"Botswana": {"size":"4"},
"Democratic Republic of Congo": {"size":"4"},
"Guinea": {"size":"4"},
"Guinea-Bissau": {"size":"4"},
"Lesotho": {"size":"4"},
"Liberia": {"size":"4"},
"Macedonia": {"size":"4"},
"Marshall Islands": {"size":"4"},
"Oman": {"size":"4"},
"Saint Lucia": {"size":"4"},
"San Marino": {"size":"4"},
"Solomon Islands": {"size":"4"},
"Yemen": {"size":"4"},
"Belize": {"size":"3"},
"Brunei": {"size":"3"},
"Cape Verde": {"size":"3"},
"Chad": {"size":"3"},
"Comoros": {"size":"3"},
"Kiribati": {"size":"3"},
"Laos": {"size":"3"},
"Liechtenstein": {"size":"3"},
"Malawi": {"size":"3"},
"Netherlands Antilles - Independent Olympic Participants (IOP)": {"size":"3"},
"Saint Vincent and The Grenadines": {"size":"3"},
"Swaziland": {"size":"3"},
"Tonga": {"size":"3"},
"Tuvalu": {"size":"3"},
"Bhutan": {"size":"2"},
"British Virgin Islands": {"size":"2"},
"Dominica": {"size":"2"},
"East Timor": {"size":"2"},
"Equatorial Guinea": {"size":"2"},
"Gambia": {"size":"2"},
"Mauritania": {"size":"2"},
"Nauru": {"size":"2"},
"São Tomé and Príncipe": {"size":"2"},
"Sierra Leone": {"size":"2"},
"Somalia": {"size":"2"},
"South Sudan": {"size":"1"}
}