var gdata = {
	"tooltip":{},
    "shapes":[
    	{
	    	"type":"zingchart.maps",
	    	"options":{
	    		"id":"map",
	    		"name":"world.continents",
	    		"scale":true,
	    		"x":0,
	    		"y":0,
	    		"width":640,
	    		"height":430,
	    		"style":{
	    			"static":true,
		    		"items":{
		    			"EUROPE":{
		    				"static":false,
		    				"backgroundColor":"#f90",
		    				"hoverState":{
		    					"backgroundColor":"#c60",
		    				}
		    			},
		    			"NORTHAMERICA":{
		    				"static":false,
		    				"backgroundColor":"#f90",
		    				"hoverState":{
		    					"backgroundColor":"#c60",
		    				}
		    			}
		    		}
	    		}
	    	}
    	}
	]
}