zingchart.THEMES.tutorials = {
	"root":{
		"style":{
			".indicator":{
				"background-color":"#333",
				"width":30,
				"height":30,
				"padding":5,
				"color":"#fff",
				"font-size":13,
				"border-radius":15,
				"border-width":3,
				"border-color":"#fff",
				"shadow":true,
				"shadow-angle":90,
				"shadow-distance":3,
				"shadow-alpha":0.5
			},
			".tooltip":{
				"background-color":"#369",
				"padding":10,
				"color":"#fff",
				"font-size":10,
				"border-radius":5,
				"border-width":2,
				"border-color":"#fff",
				"shadow":true,
				"shadow-angle":90,
				"shadow-distance":3,
				"shadow-alpha":0.5
			}
		}
	}
};