var gdata = {
"graphset":[
    {
        "type":"area",
        "stacked":"true",
        "alpha":1,
        "background-image":"images/retro_bg.jpg",
        "plotarea":{
            "margin":"100px 40px 60px 60px"
        },
        "title":{
            "text":"TOP DOWNLOADED ARTIST",
            "font-family":"Trebuchet MS",
            "font-size":"28px",
            "font-color":"#93B7C5",
            "background-color":-1,
            "margin-top":"15px",
            "margin-right":"15px",
            "margin-bottom":"10px",
            "text-align":"right"
        },
        "legend":{
            "layout":"1x4",
            "position":"55% 15%",
            "width":"400px",
            "height":"40px",
            "visible":true,
            "background-color":-1,
            "border-width":"0px",
            "item":{
                "font-family":"Trebuchet MS",
                "font-weight":"bold",
                "font-size":11,
                "font-color":"#307C70",
                "padding":"-2 2",
                "shadow":0
            }
        },
        "scale-x":{
            "values":["Jan","Feb","Mar","Apr"],
            "line-color":"#307C70",
            "line-style":"solid",
            "line-width":"3px",
            "guide":{
                "line-color":"#ECC43B",
                "line-style":"dashed",
                "alpha":"1"
            },
            "tick":{
                "line-width":"3px",
                "line-color":"#307C70",
                "alpha":"1"
            },
            "item":{
                "font-size":"12px",
                "font-color":"#307C70",
                "font-weight":"bold",
                "font-family":"Trebuchet MS"
            },
            "minor-guide":{
                "visible":false
            }
        },
        "scale-y":{
            "values":"0:100:20",
            "line-width":"3px",
            "alpha":1,
            "line-color":"#307C70",
            "format":"%v",
            "line-style":"solid",
            "guide":{
                "line-color":"#ECC43B",
                "alpha":"1",
                "line-style":"dashed"
            },
            "tick":{
                "line-width":"3px",
                "line-color":"#307C70",
                "alpha":"1"
            },
            "item":{
                "font-size":"12px",
                "font-color":"#307C70",
                "font-weight":"bold",
                "font-family":"Trebuchet MS"
            },
            "minor-guide":{
                "visible":false
            }
        },
        "tooltip":{
            "visible":false
        },
        "value-label":{
            "font-color":"#000000"
        },
        "plot":{
            "alpha":1,
            "animate":true,
            "tooltip-text":"Series text: %t<br>Value: %v<br>Key: %k",
            "speed":0.5,
            "line-width":"5px",
            "effect":5,
            "marker":{
                "visible":false
            }
        },
        "series":[
            {
                "values":[13,18,10,25],
                "line-color":"#6FA3C1",
                "background-color":"#6FA3C1",
                "text":"Rihanna"
            },
            {
                "values":[23,9,30,14],
                "line-color":"#F79434",
                "background-color":"#F79434",
                "text":"P!nk"
            },
            {
                "values":[17,20,26,7],
                "line-color":"#7A6652",
                "background-color":"#7A6652",
                "text":"Lady Gaga"
            },
            {
                "values":[30,17,23,21],
                "line-color":"#A2A500",
                "background-color":"#A2A500",
                "text":"Ke$ha"
            }
        ]
    }
]
}