var gdata = {
"graphset":[
    {
        "type":"line",
        "stacked":true,
        "background-color":"#ffffff",
        "alpha":1,
        "plotarea":{
            "margin":"95 35 55 35"
        },
        "title":{
            "text":"Traffic Accidents 2009",
            "font-family":"helvetica",
            "font-size":"20px",
            "font-weight":"bold",
            "font-color":"#000000",
            "background-color":"#ffffff",
            "margin-top":"15px",
            "margin-left":"15px",
            "margin-bottom":"10px",
            "text-align":"left"
        },
        "legend":{
            "layout":"vertical",
            "margin":"2 5 5 380",
            "visible":true,
            "shadow":false,
            "font-family":"arial",
            "font-size":"10px",
            "background-color":"#ffffff",
            "border-width":"0px",
            "item":{
                "padding":"-2 2",
                "border-width":"0px"
            }
        },
        "scale-x":{
            "font-weight":"bold",
            "line-width":"2px",
            "line-color":"#000000",
            "line-style":"solid",
            "minor-ticks":1,
            "values":["Jan","Feb","Mar","Apr","May","Jun"],
            "guide":{
                "alpha":1,
                "visible":true,
                "line-width":"1px",
                "line-color":"#CCCCCC",
                "line-style":"solid"
            },
            "tick":{
                "size":"7px",
                "line-width":"2px",
                "placement":"outer",
                "line-color":"#000000",
                "visible":true
            },
            "minor-tick":{
                "placement":"outer",
                "alpha":0.9,
                "line-color":"#000000"
            },
            "item":{
                "font-family":"helvetica",
                "font-color":"#000000",
                "font-weight":"bold",
                "font-size":"10px",
                "visible":true
            }
        },
        "scale-y":{
            "font-weight":"bold",
            "minor-ticks":1,
            "line-width":"2px",
            "line-color":"#000000",
            "line-style":"solid",
            "format":"%v",
            "tick":{
                "size":7,
                "line-width":"2px",
                "placement":"outer",
                "line-color":"#000000",
                "visible":true
            },
            "minor-tick":{
                "placement":"outer",
                "alpha":0.9,
                "line-color":"#000000"
            },
            "item":{
                "font-family":"helvetica",
                "font-color":"#000000",
                "font-weight":"bold",
                "font-size":"10px",
                "visible":true
            },
            "guide":{
                "alpha":1,
                "visible":true,
                "line-width":"1px",
                "line-color":"#CCCCCC",
                "line-style":"solid"
            }
        },
        "crosshair-x":{
            "line-width":"2px",
            "line-color":"#000000",
            "alpha":"0.3",
            "shadow":false,
            "scale-label":{
                "visible":false
            },
            "marker":{
                "visible":false
            }
        },
        "tooltip":{
            "visible":false
        },
        "plot":{
            "alpha-area":0.4,
            "line-width":"2px",
            "alpha":1,
            "shadow":false,
            "tooltip-text":" %t: %v accidents",
            "marker":{
                "visible":false
            }
        },
        "series":[
            {
                "values":[21,15,26,23,27,22],
                "text":"Pedestrians",
                "line-color":"#c0c0c0"
            },
            {
                "values":[18,25,19,7,20,16],
                "text":"Motorcycles",
                "line-color":"#959595"
            },
            {
                "values":[18,25,19,27,20,16],
                "text":"Trucks",
                "line-color":"#5e5e5e"
            },
            {
                "values":[18,25,19,17,20,16],
                "text":"Cars",
                "line-color":"#272727"
            }
        ]
    }
]
}