var gdata = {
"graphset":[
    {
        "type":"line",
        "background-color":"#ffffff",
        "scale-x":{
            "line-color":"#ffffff",
            "values":["Jan","Feb","Mar","Apr","May","Jun"],
            "guide":{
                "visible":false
            },
            "tick":{
                "visible":false
            },
            "item":{
                "font-family":"helvetica",
                "font-color":"#05636c",
                "font-weight":"bold",
                "font-size":"12px",
                "visible":true,
                "offset-y":"8px"
            }
        },
        "scale-y":{
            "values":"0:50:10",
            "line-width":"0px",
            "format":"%v",
            "tick":{
                "visible":false
            },
            "item":{
                "font-family":"helvetica",
                "font-color":"#05636c",
                "font-weight":"bold",
                "font-size":"12px",
                "visible":true,
                "offset-x":"-8px"
            },
            "guide":{
                "visible":false
            }
        },
        "crosshair-x":{
            "line-color":"#05636c",
            "marker":{
                "visible":false
            },
            "value-label":{
                "font-size":12,
                "font-color":"#ffffff",
                "border-color":"#05636c",
                "background-color":"#05636c",
                "text-align":"center",
                "border-width":"2px"
            },
            "scale-label":{
                "visible":false
            }
        },
        "tooltip":{
            "visible":false
        },
        "plot":{
            "shadow-alpha":0,
            "line-style":"solid",
            "line-width":"2px",
            "tooltip-text":" %v  %t <br/> Key: %k",
            "marker":{
                "visible":false
            }
        },
        "series":[
            {
                "values":[8,5,9,7,5,16,8],
                "text":"Shoes",
                "line-color":"#9bc1c4",
                "background-color":"#9bc1c4"
            },
            {
                "values":[10,15,16,23,15,22,20],
                "text":"Pants",
                "line-style":"dotted",
                "line-color":"#69a1a7",
                "background-color":"#69a1a7"
            },
            {
                "values":[35,24,23,12,28,21,36],
                "text":"Accessories",
                "line-color":"#378289",
                "background-color":"#378289"
            },
            {
                "values":[45,38,29,39,33,25,47],
                "text":"Bags",
                "line-style":"dashed",
                "line-color":"#05636c",
                "background-color":"#05636c"
            }
        ]
    }
]
}